version: "3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
      - "9200:9200"
    environment:
      - node.name=elastic
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=elastic
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
